# Write a github actions workflow that does the following:
# Tests the code using Jest and the pre-built `npm run test` command
# Builds a docker image using the Dockerfile that you have written
# Pushes the docker image to your GitHub Container Registry repository
# Releases your newly pushed image to your Railway service using the Railway CLI

name: take-home-assessment-5123213

on:
  push:
    branches:
      - main

jobs:
  # Enter your job steps here
  build:
    runs-on: ubuntu-latest
     steps:
    - name: Checkout code
      uses: actions/checkout@v2
     - name: Use Node.js v14.x
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
     - name: Install dependencies
      run: npm install
     - name: Run tests
      run: npm test
     - name: Build Docker image
      run: docker build . -t ${{ github.repository }}

     - name: Login to GitHub Container Registry
       run: echo $CR_PAT | docker login ghcr.io -u amarshaik012--password-stdin
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
     - name: Push to GitHub Container Registry
      run: docker push ghcr.io/${{ github.repository }}
     - name: Install Railway CLI
      run: curl -sSL https://get.railway.app | bash
     - name: Authenticate with Railway
      run: railway login
     - name: Deploy to Railway
      env:
        RAILWAY_URL: ${{ secrets.RAILWAY_URL }}
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      run: railway deploy
